spring:
  datasource:
    url: jdbc:mysql://128.199.249.15:3306/reportsystem
    username: root
    password: 1213@A*#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
    port: 8081
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

logging:
  level:
    org.springframework.security: DEBUG
