spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportsystem
    username: postgres
    password: 123_password
#    url: jdbc:mysql://localhost:3306/reportsystem
#    username: root
#    password: 1234!@#$
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8989
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
logging:
  level:
    org.springframework.security: DEBUG