spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportsystem
    username: postgres
    password: 123_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
