name: RS API - CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Working Directory
        run: |
          WORKING_DIR="$(pwd)"
          echo "Setting working directory to: $WORKING_DIR"
        shell: bash

      - name: Build with Gradle
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          gradle clean build

      - name: Stop and remove Docker container
        run: |
          docker stop rs_api || true
          docker rm rs_api || true
          docker rmi rs_api || true
        continue-on-error: true

      - name: Build the Docker image
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          docker build -t rs_api .

      - name: Run Docker container
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          docker run -d --name rs_api -p 8081:8081 --restart always rs_api
